### ISSUE TITLE
Integrate Webpack

### ISSUE THREAD

**Issue by bewards** [mkalthoum/Sadah#1]
**Instructions**
- Integrate Webpack in order to bundle javascript (vendor libraries and your own js modules), sass/scss (bootstrap-sass and your own scss modules), and deploying html files. Follow this tutorial: https://stevenwestmoreland.com/2018/01/how-to-include-bootstrap-in-your-project-with-webpack.html

**Comment by mkalthoum** [comment]
Some minor hiccups, but all resolved.
![success](https://user-images.githubusercontent.com/17127843/41511461-fd29abfa-7244-11e8-99ea-d488a8df994b.PNG)
